### ISSUE TITLE
Mention Python version for installing sqlitebck

### ISSUE THREAD

**Issue by rvanlaar** [harelba/q#262]
I installed sqlitebck, but I can't use the 'fast' storage method.
It seems to have to do that `q` uses a different python version.

Please mention the right python version to use in the docs.
```
# python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlitebck
```
q output:
```Saving data to db file data.db
sqlitebck python module cannot be found - fast store to disk cannot be performed. Note that for now, sqlitebck is not packaged as part of q. In order to use the fast method, you need to manually `pip install sqlitebck` into your python environment. We obviously consider this as a bug and it will be fixed once proper packaging will be done, making the fast method the standard one.
Traceback (most recent call last):
  File "bin/q.py", line 294, in store_db_to_disk_fast
ModuleNotFoundError: No module named 'sqlitebck'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/q.py", line 1551, in _execute
  File "bin/q.py", line 310, in store_db_to_disk
  File "bin/q.py", line 297, in store_db_to_disk_fast
MissingSqliteBckModuleException: sqlitebck python module cannot be found - fast store to disk cannot be performed. Note that for now, sqlitebck is not packaged as part of q. In order to use the fast method, you need to manually `pip install sqlitebck` into your python environment. We obviously consider this as a bug and it will be fixed once proper packaging will be done, making the fast method the standard one.
```

And pip3 installation output:
```
pip3 install sqlitebck
Requirement already satisfied: sqlitebck in /usr/local/lib/python3.9/dist-packages (1.4)
```

**Comment by harelba** [comment]
Thanks for finding this. I'm going to release a new version of q some time soon, and this issue with be fixed there.

Unfortunately, q's currently packaged with a self-contained python version, so installing sqlitebck inside it is impossible, i'm afraid.
